# Generated by Django 2.0.7 on 2019-08-28 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userProfile', '0002_auto_20190828_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerFarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('land_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('type_of_crops_produce', models.CharField(blank=True, max_length=30, null=True)),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.Address')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_producerfarm_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_producerfarm_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProducerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('product_time', models.DateTimeField(auto_now=True)),
                ('amount_of_prodect', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_producerproduct_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_producerproduct_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
