# Generated by Django 2.0.7 on 2019-09-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerproduct',
            old_name='amount_of_prodect',
            new_name='amount_of_product',
        ),
    ]
