# Generated by Django 2.2.5 on 2019-12-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_auto_20191204_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
