# Generated by Django 2.2.5 on 2020-01-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_auto_20200120_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producerbulkrequest',
            options={'verbose_name': 'producer product', 'verbose_name_plural': 'Producer Bulk Request'},
        ),
        migrations.RenameField(
            model_name='historicalproducerbusiness',
            old_name='productbusiness_geopoint',
            new_name='product_business_geopoint',
        ),
        migrations.RenameField(
            model_name='producerbusiness',
            old_name='productbusiness_geopoint',
            new_name='product_business_geopoint',
        ),
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='micro_bulk_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.MicroBulkOrder'),
        ),
    ]
