# Generated by Django 2.2.5 on 2019-11-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191027_1129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0002_auto_20190912_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_businesstype_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_businesstype_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='amount_of_product',
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='product_time',
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='delivery_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='product_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='producer/product'),
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='product_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='production_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='unit_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProducerBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('business_image', models.ImageField(blank=True, null=True, upload_to='producer/business')),
                ('total_employees', models.IntegerField()),
                ('land_amount', models.CharField(blank=True, max_length=30, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.BusinessType')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_producerbusiness_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_producerbusiness_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
