# Generated by Django 2.2.5 on 2019-11-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0002_auto_20191126_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducerbulkrequest',
            name='status',
            field=models.CharField(choices=[('PDNG', 'Pending'), ('ACPTD', 'Accepted')], default='PDNG', max_length=20),
        ),
        migrations.AddField(
            model_name='producerbulkrequest',
            name='status',
            field=models.CharField(choices=[('PDNG', 'Pending'), ('ACPTD', 'Accepted')], default='PDNG', max_length=20),
        ),
    ]
