# Generated by Django 2.2.5 on 2019-11-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_auto_20191127_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducerbulkrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='bulk_order_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.BulkOrderProducts'),
        ),
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='micro_bulk_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.MicroBulkOrder'),
        ),
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order'),
        ),
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=20),
        ),
    ]
