# Generated by Django 2.2.5 on 2019-12-05 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0003_auto_20191204_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbulkorder',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
