# Generated by Django 2.2.5 on 2019-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20191104_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerbusiness',
            name='total_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
