# Generated by Django 2.2.5 on 2019-11-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20191127_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='hex_code',
            field=models.CharField(default='none', max_length=20, unique=True),
        ),
    ]
