# Generated by Django 2.2.5 on 2020-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20200216_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkorderproducts',
            name='available_qty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
