# Generated by Django 2.2.5 on 2020-01-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0004_auto_20191205_0358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producerbulkrequest',
            options={'verbose_name_plural': 'producer products'},
        ),
    ]
