# Generated by Django 2.2.5 on 2020-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0005_auto_20200107_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducerbulkrequest',
            name='product_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='পন্যের নাম'),
        ),
        migrations.AddField(
            model_name='producerbulkrequest',
            name='product_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='পন্যের নাম'),
        ),
    ]
