# Generated by Django 2.2.5 on 2019-11-27 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0005_auto_20191127_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMicroBulkOrderProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('qty', models.FloatField(default=0.0)),
                ('shareable_ref_code', models.CharField(default='none', max_length=20, unique=True)),
                ('accepted_ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_customermicrobulkorderproductrequest_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('micro_bulk_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.MicroBulkOrderProducts')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_customermicrobulkorderproductrequest_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
