# Generated by Django 2.2.5 on 2019-11-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_auto_20191111_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducerbusiness',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproducerfarm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalproducerproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producerbusiness',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producerfarm',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
