# Generated by Django 2.2.5 on 2019-11-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0006_customermicrobulkorderproductrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.ProducerBulkRequest'),
        ),
    ]
