# Generated by Django 2.2.5 on 2019-11-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0007_auto_20191127_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='hex_code',
            field=models.CharField(blank=True, default='none', max_length=20, null=True, unique=True),
        ),
    ]
