# Generated by Django 2.2.5 on 2019-11-21 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0014_auto_20191121_0704'),
        ('producer', '0007_auto_20191119_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProducerBulkRequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.TextField(blank=True, max_length=100, null=True)),
                ('production_time', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.FloatField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('general_price', models.FloatField(blank=True, null=True)),
                ('general_qty', models.FloatField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('offer_qty', models.FloatField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('general_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.ProductUnit')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('offer_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.ProductUnit')),
                ('product_category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.ProductCategory')),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.ProductUnit')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical producer bulk request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProducerBulkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='producer/product')),
                ('production_time', models.DateTimeField(blank=True, null=True)),
                ('unit_price', models.FloatField()),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('general_price', models.FloatField(blank=True, null=True)),
                ('general_qty', models.FloatField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('offer_qty', models.FloatField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_producerbulkrequest_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('general_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_unit', to='product.ProductUnit')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_producerbulkrequest_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('offer_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_unit', to='product.ProductUnit')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_unit', to='product.ProductUnit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='producerproduct',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalProducerProduct',
        ),
        migrations.DeleteModel(
            name='ProducerProduct',
        ),
    ]
