# Generated by Django 2.2.5 on 2019-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0008_auto_20191127_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='qty',
            field=models.FloatField(default=0),
        ),
    ]
