# Generated by Django 2.2.5 on 2019-11-21 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0008_auto_20191121_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='general_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_unit', to='product.ProductUnit'),
        ),
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='offer_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_unit', to='product.ProductUnit'),
        ),
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
