# Generated by Django 2.2.5 on 2019-11-21 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0009_auto_20191121_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
