# Generated by Django 2.2.5 on 2019-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0009_auto_20191127_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermicrobulkorderproductrequest',
            name='accepted_ref_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customermicrobulkorderproductrequest',
            name='shareable_ref_code',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
