# Generated by Django 2.2.5 on 2019-11-21 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0010_auto_20191121_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_unit', to='product.ProductUnit'),
        ),
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
