# Generated by Django 2.2.5 on 2019-11-21 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191121_0704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0011_auto_20191121_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=20)),
                ('expire_date', models.DateTimeField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BulkOrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_price', models.FloatField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('target_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.BulkOrder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
