# Generated by Django 2.2.5 on 2019-11-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0011_auto_20191127_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermicrobulkorderproductrequest',
            name='shareable_ref_code',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
