# Generated by Django 2.2.5 on 2019-11-28 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0012_auto_20191127_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkorder',
            name='hex_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bulkorderproducts',
            name='bulk_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_orders_products', to='producer.BulkOrder'),
        ),
        migrations.AlterField(
            model_name='bulkorderproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_order_products', to='producer.ProducerBulkRequest'),
        ),
        migrations.AlterField(
            model_name='microbulkorder',
            name='bulk_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micro_bulk_order', to='producer.BulkOrder'),
        ),
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='bulk_order_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micro_bulk_order_products', to='producer.BulkOrderProducts'),
        ),
    ]
