# Generated by Django 2.2.5 on 2019-11-21 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20191121_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0012_bulkorder_bulkorderproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicroBulkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.BulkOrder')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MicroBulkOrderProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bulk_order_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.BulkOrderProducts')),
                ('micro_bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.MicroBulkOrder')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
