# Generated by Django 2.2.5 on 2019-11-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0013_microbulkorder_microbulkorderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducerbulkrequest',
            name='general_unit',
        ),
        migrations.RemoveField(
            model_name='historicalproducerbulkrequest',
            name='offer_unit',
        ),
        migrations.RemoveField(
            model_name='historicalproducerbulkrequest',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='producerbulkrequest',
            name='general_unit',
        ),
        migrations.RemoveField(
            model_name='producerbulkrequest',
            name='offer_unit',
        ),
        migrations.RemoveField(
            model_name='producerbulkrequest',
            name='unit',
        ),
    ]
