# Generated by Django 2.2.5 on 2019-11-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0014_auto_20191128_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='bulk_order_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcop', to='producer.BulkOrderProducts'),
        ),
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='micro_bulk_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcop', to='producer.MicroBulkOrder'),
        ),
    ]
