# Generated by Django 2.2.5 on 2019-11-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('producer', '0014_auto_20191122_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='microbulkorderproducts',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_microbulkorderproducts_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='microbulkorderproducts',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='microbulkorderproducts',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_microbulkorderproducts_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='microbulkorderproducts',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producerbulkrequest',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producerbusiness',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producerfarm',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='BulkOrderReqConntr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('bulk_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.BulkOrder')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_producer_bulkorderreqconntr_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_producer_bulkorderreqconntr_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('producer_bulk_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.ProducerBulkRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
