# Generated by Django 2.2.5 on 2019-11-29 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0015_auto_20191128_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermicrobulkorderproductrequest',
            name='micro_bulk_order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producer.MicroBulkOrderProducts'),
        ),
    ]
