# Generated by Django 2.2.5 on 2019-11-29 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0016_auto_20191129_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermicrobulkorderproductrequest',
            name='micro_bulk_order_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmbopr', to='producer.MicroBulkOrderProducts'),
        ),
    ]
