# Generated by Django 2.2.5 on 2019-12-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0017_auto_20191129_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microbulkorderproducts',
            name='bulk_order_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.BulkOrderProducts'),
        ),
    ]
