# Generated by Django 2.2.5 on 2020-01-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('product', '0001_initial'),
        ('producer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldeliverychecklisttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklisttemplate',
            name='delivery_check_list',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='delivery.DeliveryCheckList'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklisttemplate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklisttemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklisttemplate',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklistitem',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklistitem',
            name='delivery_check_list',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='delivery.DeliveryCheckList'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklistitem',
            name='handed_over_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklistitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklistitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklistitem',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.Product'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='assigned_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='producer_bulk_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='producer.ProducerBulkRequest'),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='retailer_accept_order',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retailer.AcceptedOrder'),
        ),
        migrations.AddField(
            model_name='deliverychecklisttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_delivery_deliverychecklisttemplate_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='deliverychecklisttemplate',
            name='delivery_check_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryCheckList'),
        ),
        migrations.AddField(
            model_name='deliverychecklisttemplate',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_delivery_deliverychecklisttemplate_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='deliverychecklisttemplate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='deliverychecklistitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_delivery_deliverychecklistitem_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='deliverychecklistitem',
            name='delivery_check_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.DeliveryCheckList'),
        ),
        migrations.AddField(
            model_name='deliverychecklistitem',
            name='handed_over_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverychecklistitem',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_delivery_deliverychecklistitem_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='deliverychecklistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='deliverychecklist',
            name='assigned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverychecklist',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_delivery_deliverychecklist_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='deliverychecklist',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_delivery_deliverychecklist_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='deliverychecklist',
            name='producer_bulk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.ProducerBulkRequest'),
        ),
        migrations.AddField(
            model_name='deliverychecklist',
            name='retailer_accept_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.AcceptedOrder'),
        ),
    ]
