# Generated by Django 2.2.5 on 2019-11-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverychecklist',
            old_name='produecer_bulk_request',
            new_name='producer_bulk_request',
        ),
        migrations.RenameField(
            model_name='historicaldeliverychecklist',
            old_name='produecer_bulk_request',
            new_name='producer_bulk_request',
        ),
    ]
