# Generated by Django 2.2.5 on 2019-11-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191124_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychecklist',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldeliverychecklist',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverychecklist',
            name='producer_bulk_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producer.ProducerBulkRequest'),
        ),
        migrations.AlterField(
            model_name='deliverychecklist',
            name='retailer_accept_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.AcceptedOrder'),
        ),
    ]
