# Generated by Django 2.2.5 on 2020-02-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200121_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychecklist',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverychecklistitem',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverychecklisttemplate',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeliverychecklist',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeliverychecklistitem',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldeliverychecklisttemplate',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
