# Generated by Django 2.0.7 on 2019-08-28 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_unit', models.CharField(blank=True, max_length=3, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_product_product_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_product_product_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type_of_product', models.CharField(max_length=90)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_product_productcategory_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_product_productcategory_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_product_productmeta_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_product_productmeta_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type_of_shop', models.CharField(max_length=89)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_product_shopcategory_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_product_shopcategory_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productmeta',
            name='shop_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ShopCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_meta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.ProductMeta'),
        ),
    ]
