# Generated by Django 2.2.5 on 2020-06-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='price_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Product Price With Vat'),
        ),
        migrations.AddField(
            model_name='historicalproductmeta',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vat Amount(%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_with_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Product Price With Vat'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vat Amount(%)'),
        ),
    ]
