# Generated by Django 2.2.5 on 2019-10-07 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductMeta'),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='shop_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ShopCategory'),
        ),
    ]
