# Generated by Django 2.2.5 on 2019-10-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191007_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
