# Generated by Django 2.2.5 on 2020-01-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191204_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='পন্যের নাম'),
        ),
        migrations.AddField(
            model_name='historicalproductcategory',
            name='type_of_product_bn',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='পন্যের ধরন'),
        ),
        migrations.AddField(
            model_name='historicalproductmeta',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='নাম'),
        ),
        migrations.AddField(
            model_name='historicalshopcategory',
            name='type_of_shop_bn',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='দোকানের ধরন'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='পন্যের নাম'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='type_of_product_bn',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='পন্যের ধরন'),
        ),
        migrations.AddField(
            model_name='productmeta',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='নাম'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='type_of_shop_bn',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='দোকানের ধরন'),
        ),
    ]
