# Generated by Django 2.2.5 on 2019-10-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191010_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
