# Generated by Django 2.2.5 on 2020-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200119_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='product_price_bn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='পন্যের মুল্য'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_bn',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='পন্যের মুল্য'),
        ),
    ]
