# Generated by Django 2.2.5 on 2019-10-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_product_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures/product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures/productcategory/'),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/pictures/productmeta/'),
        ),
    ]
