# Generated by Django 2.2.5 on 2019-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191015_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/product/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/productcategory/'),
        ),
        migrations.AlterField(
            model_name='productmeta',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/productmeta/'),
        ),
    ]
