# Generated by Django 2.2.5 on 2019-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_historicalproduct_historicalproductcategory_historicalproductmeta_historicalproductunit_historicalsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='product_last_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_last_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
