# Generated by Django 2.2.5 on 2019-11-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20191119_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductunit',
            name='product_unit',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='product_unit',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
