# Generated by Django 2.2.5 on 2019-11-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0022_auto_20191122_1527'),
        ('producer', '0014_auto_20191122_1527'),
        ('product', '0014_auto_20191121_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='productunit',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
        migrations.DeleteModel(
            name='HistoricalProductUnit',
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
    ]
