# Generated by Django 2.2.5 on 2019-10-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20191013_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_ends_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_starts_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offerproduct',
            name='offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerproduct',
            name='offer_product_balance',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_img',
            field=models.ImageField(upload_to='static/pictures/offer/%Y/%m/%d'),
        ),
    ]
