# Generated by Django 2.2.5 on 2020-01-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_auto_20200120_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffer',
            name='offer_details_bn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Offer Detail Bangla'),
        ),
        migrations.AddField(
            model_name='historicaloffer',
            name='offer_name_bn',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_details_bn',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Offer Detail Bangla'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_name_bn',
            field=models.CharField(default='Offer Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_img',
            field=models.ImageField(upload_to='offer'),
        ),
    ]
