# Generated by Django 2.2.5 on 2019-10-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20191014_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
