# Generated by Django 2.2.5 on 2020-01-08 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_auto_20200108_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproduct',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
