# Generated by Django 2.2.5 on 2019-10-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offerproduct_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_img',
            field=models.ImageField(upload_to='pictures/offer/%Y/%m/%d'),
        ),
    ]
