# Generated by Django 2.2.5 on 2019-10-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_auto_20191015_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_img',
            field=models.ImageField(upload_to='offer/%Y/%m/%d'),
        ),
    ]
