# Generated by Django 2.2.5 on 2019-11-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_historicaloffer_historicalofferproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
