# Generated by Django 2.2.5 on 2019-11-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20191119_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalofferproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerproduct',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
