# Generated by Django 2.2.5 on 2019-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_auto_20191119_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
