# Generated by Django 2.0.7 on 2019-08-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accuntName',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='accuntNo',
            new_name='account_no',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='bankName',
            new_name='bank_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='retailerID',
            new_name='retailer_id',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='retailerEmail',
            new_name='retailer_email',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='retailerLogo',
            new_name='retailer_logo',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='remailerWebsite',
            new_name='retailer_website',
        ),
        migrations.RenameField(
            model_name='retailer',
            old_name='userID',
            new_name='user',
        ),
    ]
