# Generated by Django 2.2.5 on 2020-01-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_auto_20200121_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='product',
            new_name='shodai_products',
        ),
        migrations.AlterField(
            model_name='historicalshopproduct',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.Product', verbose_name='Shodai Product'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='Shodai Product'),
        ),
    ]
