# Generated by Django 2.2.5 on 2020-01-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_auto_20200122_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='shodai_products',
        ),
    ]
