# Generated by Django 2.2.5 on 2019-12-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_auto_20191229_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedorder',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.Shop'),
        ),
    ]
