# Generated by Django 2.2.5 on 2020-01-30 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_remove_shop_shodai_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshopproduct',
            name='product_meta',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='product_meta',
        ),
    ]
