# Generated by Django 2.2.5 on 2019-12-29 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_auto_20191229_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshopproduct',
            name='shop',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='retailer.Shop'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.Shop'),
        ),
    ]
