# Generated by Django 2.2.5 on 2020-02-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0007_auto_20200201_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshopproduct',
            name='product_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='product_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
