# Generated by Django 2.2.5 on 2019-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0008_auto_20191017_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
