# Generated by Django 2.2.5 on 2019-10-19 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191017_0622'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retailer', '0010_auto_20191019_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_retailer_acceptedorder_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_retailer_acceptedorder_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderProduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
