# Generated by Django 2.2.5 on 2019-10-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0011_acceptedorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedorder',
            name='order_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.OrderProduct'),
        ),
    ]
