# Generated by Django 2.2.5 on 2019-10-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0012_auto_20191019_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedorder',
            old_name='oder',
            new_name='order',
        ),
    ]
