# Generated by Django 2.2.5 on 2019-10-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191027_1129'),
        ('retailer', '0014_auto_20191026_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.ShopCategory'),
            preserve_default=False,
        ),
    ]
