# Generated by Django 2.2.5 on 2019-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20191027_1129'),
        ('retailer', '0015_shop_shop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
