# Generated by Django 2.2.5 on 2019-11-11 10:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0016_shop_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_geopoint',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
