# Generated by Django 2.2.5 on 2019-11-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0018_historicalacceptedorder_historicalaccount_historicalshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshop',
            name='shop_close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalshop',
            name='shop_open_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_close_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_open_time',
            field=models.TimeField(null=True),
        ),
    ]
