# Generated by Django 2.2.5 on 2019-11-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0021_historicalshopproduct_shopproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalshopproduct',
            name='product_unit',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='product_unit',
        ),
    ]
