# Generated by Django 2.2.5 on 2019-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0022_auto_20191122_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedorder',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
