# Generated by Django 2.2.5 on 2019-11-22 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0015_auto_20191122_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeSellRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('qty', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
