# Generated by Django 2.2.5 on 2020-01-20 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('market', '0001_initial'),
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesellrate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Location'),
        ),
        migrations.AddField(
            model_name='wholesellrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='wholesellrate',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.ProductUnit'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_market_kitchenmarket_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Location'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_market_kitchenmarket_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Area'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_market_unit', to='utility.ProductUnit'),
        ),
        migrations.AddField(
            model_name='kitchenmarket',
            name='whole_sell_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whole_sell_unit', to='utility.ProductUnit'),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_market_commissionrate_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_market_commissionrate_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='polygon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Area'),
        ),
        migrations.AddField(
            model_name='commissionrate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
