# Generated by Django 2.2.5 on 2019-11-22 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0002_auto_20191122_1548'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0016_auto_20191122_1548'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesellrate',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Location'),
        ),
        migrations.AddField(
            model_name='wholesellrate',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.ProductUnit'),
        ),
        migrations.CreateModel(
            name='KitchenMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qty', models.FloatField()),
                ('whole_sell_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('whole_sell_qty', models.FloatField()),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created it', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_market_kitchenmarket_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utility.Location')),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_market_kitchenmarket_set', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Area')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_market_unit', to='utility.ProductUnit')),
                ('whole_sell_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whole_sell_unit', to='utility.ProductUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
