# Generated by Django 2.2.5 on 2020-02-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200121_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshopinventory',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopinventory',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopinventoryhistory',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
