# Generated by Django 2.0.7 on 2019-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20190903_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userType',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('CM', 'Customer'), ('RT', 'Retailer'), ('PD', 'Producer'), ('SF', 'Staff')], default='CM', max_length=30),
        ),
    ]
