# Generated by Django 2.2.5 on 2019-09-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_auto_20190903_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=11, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of otp sent')),
                ('logged', models.BooleanField(default=False, help_text='If otp verification got successful')),
                ('forgot', models.BooleanField(default=False, help_text='Only true if forgot password')),
                ('forgot_logged', models.BooleanField(default=False, help_text='Only true if otp  verified for forgot password')),
            ],
        ),
    ]
