# Generated by Django 2.2.5 on 2019-10-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20191007_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_NID',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
