# Generated by Django 2.2.5 on 2019-10-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_auto_20191016_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='user/qr_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(default=1, upload_to='user/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
