# Generated by Django 2.2.5 on 2019-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_auto_20191026_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='qr_code',
        ),
    ]
