# Generated by Django 2.2.5 on 2019-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0013_remove_userprofile_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='user/%Y/%m/%d'),
        ),
    ]
