# Generated by Django 2.2.5 on 2019-11-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_auto_20191027_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_NID',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
