# Generated by Django 2.2.5 on 2019-11-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_historicaladdress_historicalblacklistedtoken_historicalotp_historicaluserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
