# Generated by Django 2.2.5 on 2019-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionrate',
            name='product',
        ),
    ]
