# Generated by Django 2.2.5 on 2019-11-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0004_remove_commissionrate_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommissionRate',
        ),
    ]
