# Generated by Django 2.2.5 on 2020-01-21 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('due', '0001_initial'),
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdueshistory',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer.Shop'),
        ),
    ]
