# Generated by Django 2.0.7 on 2019-08-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField()),
                ('delivery_date_time', models.DateTimeField()),
                ('delivery_place', models.CharField(max_length=100)),
                ('order_status', models.CharField(max_length=100)),
            ],
        ),
    ]
