# Generated by Django 2.2.5 on 2020-06-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderproduct',
            name='order_product_price_with_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalorderproduct',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vat Amount(%)'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_product_price_with_vat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Vat Amount(%)'),
        ),
    ]
