# Generated by Django 2.2.5 on 2020-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200625_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentinfo',
            old_name='order',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot',
            field=models.CharField(blank=True, help_text='Auto Save', max_length=100, null=True),
        ),
    ]
