# Generated by Django 2.2.5 on 2020-01-07 06:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191204_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='order_geopoint',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='order',
            name='order_geopoint',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
