# Generated by Django 2.2.5 on 2020-06-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200625_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='net_pay_able_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total Vat'),
        ),
        migrations.AddField(
            model_name='order',
            name='net_pay_able_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Total Vat'),
        ),
    ]
