# Generated by Django 2.0.7 on 2019-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190828_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('OD', 'Ordered'), ('RE', 'Order Ready'), ('OAD', 'Order At Delivery'), ('COM', 'Order Completed'), ('CN', 'Order Cancelled')], default='OD', max_length=100),
        ),
    ]
