# Generated by Django 2.2.5 on 2020-02-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_deliverycharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvat',
            name='vat_amount',
            field=models.FloatField(default=0, verbose_name='Vat Amount(%)'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='product_meta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductMeta'),
        ),
        migrations.AlterField(
            model_name='vat',
            name='vat_amount',
            field=models.FloatField(default=0, verbose_name='Vat Amount(%)'),
        ),
    ]
