# Generated by Django 2.2.5 on 2019-10-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191015_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='orderproduct_qty',
            field=models.FloatField(default=1),
        ),
    ]
