# Generated by Django 2.2.5 on 2019-10-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderproduct_orderproduct_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('FP', 'Fixed Price'), ('BD', 'Biding')], default='FP', max_length=20),
        ),
    ]
