# Generated by Django 2.2.5 on 2019-10-16 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191015_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vat',
            name='product_meta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.ProductMeta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vat',
            name='vat_amount',
            field=models.FloatField(default=0),
        ),
    ]
