# Generated by Django 2.2.5 on 2019-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20191016_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='orderproduct_qty',
            new_name='order_product_qty',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_product_price',
            field=models.FloatField(default=0),
        ),
    ]
