# Generated by Django 2.2.5 on 2019-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191024_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('OD', 'Ordered'), ('OA', 'Order Accepted'), ('RE', 'Order Ready'), ('OAD', 'Order At Delivery'), ('COM', 'Order Completed'), ('CN', 'Order Cancelled')], default='OD', max_length=100),
        ),
    ]
