# Generated by Django 2.2.5 on 2019-10-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20191027_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total_price',
            field=models.FloatField(default=0),
        ),
    ]
