# Generated by Django 2.2.5 on 2019-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20191121_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vat',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
