# Generated by Django 2.2.5 on 2019-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20191122_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvat',
            name='product_meta',
        ),
        migrations.RemoveField(
            model_name='vat',
            name='product_meta',
        ),
    ]
