# Generated by Django 2.2.5 on 2019-11-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20191125_0900'),
        ('order', '0017_auto_20191125_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvat',
            name='product_meta',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.ProductMeta'),
        ),
        migrations.AddField(
            model_name='vat',
            name='product_meta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.ProductMeta'),
        ),
    ]
